### ISSUE TITLE
Add Standard Docs

### ISSUE THREAD

**Issue by reizuseharu** [reizuseharu/Diana#18]
### Description
Add standard documents to repository

### Details
Documents:
- Vision
- Requirements
- Design

### Acceptance Criteria
- README updated with relevant setup
- Add docs written

### Tasks
- [ ] Update README
- [ ] Write Vision doc
- [ ] Write Requirements doc
- [ ] Write Design doc
