### ISSUE TITLE
Add Client

### ISSUE THREAD

**Issue by reizuseharu** [reizuseharu/Diana#20]
### Description
Add Client Class for accessing endpoints

### Details
Need a client class as a standard REST Client design

### Acceptance Criteria
- Client capable of accessing SRC endpoints

### Tasks
- [ ] Implement Client interface
- [ ] Add Client Class
- [ ] Add Unit Tests
